server:
  port: 3000
  ## 들여쓰기 = 하위 속성 | : 뒤에 1칸씩 띄어 써야 인식함
spring:
  # 데이터 베이스 설정
  datasource: # @Bean 빈 은 내부에서 설정해 줌
    driverClassName: oracle.jdbc.driver.OracleDriver # driver-class-name 형태도 가능 | oracle driver 설정
    url: jdbc:oracle:thin:@localhost:1521:XE # url 주소
    username: ${db.username} # 환경 변수로 등록 -> 절대 노출 X
    password: ${db.password} # 환경 변수로 등록 -> 절대 노출 X
  ## spring 하위 속성
  # JPA 설정
  jpa:
    properties:
      show_sql: true # 실행하는 SQL 을 콘솔에 출력
      format_sql: true # 실행되는 SQL 의 들여쓰기 및 줄 개행 -> 없으면 1줄로 나옴
      use_sql_comments: true # 주석 관련