server:
  port: 3000

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json # 요청 헤더 의 content-type
  default-produces-media-type: application/json # 응답 헤더 의 content-type
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /apidocs.html
    disable-swagger-default-url: true
  paths-to-match: # 특정 url 로 가는 url 만 연결 가능
    - /api/** # /api/ 뒤의 모든 경로 -> 자동 문서로 만들어주는 범위로 설정